//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damir_Filipovic_HCI2023.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageESP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageESP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Damir_Filipovic_HCI2023.Properties.LanguageESP", typeof(LanguageESP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Bolsa.
        /// </summary>
        internal static string cartBtn {
            get {
                return ResourceManager.GetString("cartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Placas base.
        /// </summary>
        internal static string componentMotherboardBtn {
            get {
                return ResourceManager.GetString("componentMotherboardBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Power Supply.
        /// </summary>
        internal static string componentPSBtn {
            get {
                return ResourceManager.GetString("componentPSBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Componentes.
        /// </summary>
        internal static string componentsButton {
            get {
                return ResourceManager.GetString("componentsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          CPU.
        /// </summary>
        internal static string componentsCpuBtn {
            get {
                return ResourceManager.GetString("componentsCpuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Tarjetas gráficas.
        /// </summary>
        internal static string componentsGCBtn {
            get {
                return ResourceManager.GetString("componentsGCBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          RAM.
        /// </summary>
        internal static string componentsRAMBtn {
            get {
                return ResourceManager.GetString("componentsRAMBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Juego de azar.
        /// </summary>
        internal static string gamingBtn {
            get {
                return ResourceManager.GetString("gamingBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTO/BAJO.
        /// </summary>
        internal static string highLowBtn {
            get {
                return ResourceManager.GetString("highLowBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Cerrar sesión.
        /// </summary>
        internal static string logoutBtn {
            get {
                return ResourceManager.GetString("logoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAJO/ALTO.
        /// </summary>
        internal static string lowHighBtn {
            get {
                return ResourceManager.GetString("lowHighBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar.
        /// </summary>
        internal static string orderBtn {
            get {
                return ResourceManager.GetString("orderBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDENAR.
        /// </summary>
        internal static string orderButton {
            get {
                return ResourceManager.GetString("orderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Periféricos.
        /// </summary>
        internal static string peripheralsBtn {
            get {
                return ResourceManager.GetString("peripheralsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Auriculares.
        /// </summary>
        internal static string peripheralsHeadphonesBtn {
            get {
                return ResourceManager.GetString("peripheralsHeadphonesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Teclados.
        /// </summary>
        internal static string peripheralsKeyboardBtn {
            get {
                return ResourceManager.GetString("peripheralsKeyboardBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Ratón.
        /// </summary>
        internal static string peripheralsMouseBtn {
            get {
                return ResourceManager.GetString("peripheralsMouseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Oradores.
        /// </summary>
        internal static string peripheralsSpeakersBtn {
            get {
                return ResourceManager.GetString("peripheralsSpeakersBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLASIFICAR.
        /// </summary>
        internal static string sortBtn {
            get {
                return ResourceManager.GetString("sortBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Almacenamiento.
        /// </summary>
        internal static string storageBtn {
            get {
                return ResourceManager.GetString("storageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          HDD.
        /// </summary>
        internal static string storageHDDBtn {
            get {
                return ResourceManager.GetString("storageHDDBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          SSD.
        /// </summary>
        internal static string storageSSDBtn {
            get {
                return ResourceManager.GetString("storageSSDBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Sistemas.
        /// </summary>
        internal static string systemsBtn {
            get {
                return ResourceManager.GetString("systemsBtn", resourceCulture);
            }
        }
    }
}
